# frozen_string_literal: true

source "https://rubygems.org"

gem "faraday", "~> 0.16.1"
gem "opentelemetry-api", path: "../../api"
gem "opentelemetry-common", path: "../../common"
gem "opentelemetry-instrumentation-faraday", path: "../../instrumentation/faraday"
gem "opentelemetry-instrumentation-sinatra", path: "../../instrumentation/sinatra"
gem "opentelemetry-sdk", path: "../../sdk"
gem "opentelemetry-propagator-xray", path: "../../propagator/xray"
gem "sinatra", "~> 2.0"
